sudo: false
language: haskell

git:
  depth: 5
  submodules: false

cabal: "2.4"

cache:
  directories:
  - "$HOME/.cabal/store"

matrix:
  include:
  - ghc: 8.6.5

before_install:
# Changes ssh paths into http path, so that we can do a read-only clone of
# our submodules without worrying about ssh keys.
- sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules

install:
  - ghc --version
  - cabal --version
  - git submodule update --init
  - ln -s cabal.project.dist cabal.project
  - cabal v2-configure
  - ./deps/dismantle/scripts/minify-asl.sh

script:
  - cabal v2-build --only-dependencies macaw-asl

notifications:
  email: false
