sudo: false

language: haskell
cabal: 2.4
ghc:
  - 8.4.4
  - 8.6.5

git:
  submodules: false  # whether to recursively clone submodules

cache:
  directories:
    - $HOME/.ghc
    - $HOME/.cabal

install:
# Changes ssh paths into http path, so that we can do a read-only clone of
# our submodules without worrying about ssh keys.
- sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
- git submodule update --init
- cabal v2-update --project-file=cabal.project.dist

script:
# Here starts the actual work to be performed for the package under test;
# any command which exits with a non-zero exit code causes the build to fail.
 # Build packages
 - cabal v2-test --project-file=cabal.project.dist --ghc-options="-Wall -Werror" x86 x86_symbolic
